import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const themesDir = path.join(rootDir, "themes");

const SHARED = {
  error: "#F07878",
};

const THEME_DEFINITIONS = [
  {
    fileStem: "LeoVelvet",
    label: "Leo Velvet",
    accent: "#F088C0",
    text: "#E0D8EC",
    texts: {
      light: "#352733",
    },
    backgrounds: {
      dark: "#1C1626",
      deep: "#100D16",
      light: "#FFF0F7",
    },
    paletteOverrides: {
      dark: {
        base: "#201827",
        mantle: "#1A1420",
        crust: "#15101A",
        surface0: "#2E2538",
        surface1: "#40324D",
        surface2: "#574366",
        overlay0: "#705E76",
        overlay1: "#88738F",
        overlay2: "#A38EAF",
        subtext0: "#B9A6C7",
        subtext1: "#CEBEDC",
        text: "#DED3E8",
      },
      deep: {
        base: "#14101B",
        mantle: "#100D16",
        crust: "#0C0A10",
        surface0: "#251E2E",
        surface1: "#34293F",
        surface2: "#493958",
        overlay0: "#6A5871",
        overlay1: "#83708B",
        overlay2: "#A08BAA",
        subtext0: "#B7A4C2",
        subtext1: "#CCBED9",
        text: "#DBD0E5",
      },
      light: {
        base: "#FAF0F4",
        mantle: "#F0E6EB",
        crust: "#E3DADF",
        surface0: "#F4E9EE",
        surface1: "#E9DDE4",
        surface2: "#DCD0D8",
        overlay0: "#B5A7B0",
        overlay1: "#9A8B96",
        overlay2: "#80717C",
        subtext0: "#70616E",
        subtext1: "#635360",
        text: "#554654",
      },
    },
    accents: {
      light: "#B83F82",
    },
    colorOverrides: {
      dark: {
        "list.hoverBackground": "#2E2538",
        "list.focusBackground": "#40324D",
        "list.activeSelectionBackground": "#40324D",
        "list.inactiveSelectionBackground": "#2E2538",
        "list.hoverForeground": "#DED3E8",
        "list.focusForeground": "#DED3E8",
        "quickInput.background": "#1A1420",
        "quickInput.foreground": "#DED3E8",
        "quickInputList.focusBackground": "#40324D",
        "quickInputList.focusForeground": "#DED3E8",
        "quickInputList.focusIconForeground": "#DED3E8",
        "editorSuggestWidget.selectedBackground": "#40324D",
        "editorSuggestWidget.foreground": "#DED3E8",
        "editorWidget.foreground": "#DED3E8",
        "editorHoverWidget.foreground": "#DED3E8",
        "terminal.selectionBackground": "#40324D",
        "terminal.inactiveSelectionBackground": "#2E2538",
        "terminalCursor.foreground": "#F088C0",
        "terminalCursor.background": "#201827",
        "icon.foreground": "#A38EAF",
      },
      deep: {
        "list.hoverBackground": "#251E2E",
        "list.focusBackground": "#34293F",
        "list.activeSelectionBackground": "#34293F",
        "list.inactiveSelectionBackground": "#251E2E",
        "list.hoverForeground": "#DBD0E5",
        "list.focusForeground": "#DBD0E5",
        "quickInput.background": "#100D16",
        "quickInput.foreground": "#DBD0E5",
        "quickInputList.focusBackground": "#34293F",
        "quickInputList.focusForeground": "#DBD0E5",
        "quickInputList.focusIconForeground": "#DBD0E5",
        "editorSuggestWidget.selectedBackground": "#34293F",
        "editorSuggestWidget.foreground": "#DBD0E5",
        "editorWidget.foreground": "#DBD0E5",
        "editorHoverWidget.foreground": "#DBD0E5",
        "terminal.selectionBackground": "#34293F",
        "terminal.inactiveSelectionBackground": "#251E2E",
        "terminalCursor.foreground": "#F088C0",
        "terminalCursor.background": "#14101B",
        "icon.foreground": "#A08BAA",
      },
      light: {
        "list.hoverBackground": "#E6C8D8",
        "list.focusBackground": "#E0B7CE",
        "list.activeSelectionBackground": "#E0B7CE",
        "list.inactiveSelectionBackground": "#E9D2DE",
        "list.hoverForeground": "#554654",
        "list.focusForeground": "#554654",
        "quickInput.background": "#F0E6EB",
        "quickInput.foreground": "#554654",
        "quickInputList.focusBackground": "#E0B7CE",
        "quickInputList.focusForeground": "#554654",
        "quickInputList.focusIconForeground": "#554654",
        "editorSuggestWidget.selectedBackground": "#E0B7CE",
        "activityBar.inactiveForeground": "#80717C",
        "icon.foreground": "#80717C",
      },
    },
    hues: {
      string: "#6CD8C8",
      callable: "#84B8E4",
      type: "#E0BC68",
      constant: "#F4A080",
      enum: "#88C890",
    },
    variantHues: {
      light: {
        string: "#007A73",
        callable: "#2B6F9F",
        type: "#8F6500",
        constant: "#B85A35",
        enum: "#4F873F",
      },
    },
  },
  {
    fileStem: "LeoDew",
    label: "Leo Dew",
    accent: "#C48EF0",
    text: "#E0DEE8",
    texts: {
      light: "#2C253D",
    },
    backgrounds: {
      dark: "#1A1828",
      deep: "#0D0B14",
      light: "#F5F1FF",
    },
    paletteOverrides: {
      dark: {
        base: "#1B192B",
        mantle: "#171523",
        crust: "#12101D",
        surface0: "#29263A",
        surface1: "#39334F",
        surface2: "#4D4566",
        overlay0: "#696176",
        overlay1: "#817891",
        overlay2: "#9B92B2",
        subtext0: "#B1A9C8",
        subtext1: "#C7C1DC",
        text: "#D8D4E8",
      },
      deep: {
        base: "#11101A",
        mantle: "#0E0D15",
        crust: "#0A0910",
        surface0: "#201D2D",
        surface1: "#2E2841",
        surface2: "#413957",
        overlay0: "#635B72",
        overlay1: "#7A718D",
        overlay2: "#968BAD",
        subtext0: "#AEA6C4",
        subtext1: "#C5BEDB",
        text: "#D5D0E5",
      },
      light: {
        base: "#F3F1FA",
        mantle: "#E9E7F1",
        crust: "#DDDCE7",
        surface0: "#EDEAF5",
        surface1: "#E1DEEC",
        surface2: "#D4D1E0",
        overlay0: "#AAA6B7",
        overlay1: "#8F899F",
        overlay2: "#756D86",
        subtext0: "#665D78",
        subtext1: "#584F6B",
        text: "#4D455F",
      },
    },
    accents: {
      light: "#8B4CC8",
    },
    colorOverrides: {
      dark: {
        "list.hoverBackground": "#29263A",
        "list.focusBackground": "#39334F",
        "list.activeSelectionBackground": "#39334F",
        "list.inactiveSelectionBackground": "#29263A",
        "list.hoverForeground": "#D8D4E8",
        "list.focusForeground": "#D8D4E8",
        "quickInput.background": "#171523",
        "quickInput.foreground": "#D8D4E8",
        "quickInputList.focusBackground": "#39334F",
        "quickInputList.focusForeground": "#D8D4E8",
        "quickInputList.focusIconForeground": "#D8D4E8",
        "editorSuggestWidget.selectedBackground": "#39334F",
        "editorSuggestWidget.foreground": "#D8D4E8",
        "editorWidget.foreground": "#D8D4E8",
        "editorHoverWidget.foreground": "#D8D4E8",
        "terminal.selectionBackground": "#39334F",
        "terminal.inactiveSelectionBackground": "#29263A",
        "terminalCursor.foreground": "#C48EF0",
        "terminalCursor.background": "#1B192B",
        "icon.foreground": "#9B92B2",
      },
      deep: {
        "list.hoverBackground": "#201D2D",
        "list.focusBackground": "#2E2841",
        "list.activeSelectionBackground": "#2E2841",
        "list.inactiveSelectionBackground": "#201D2D",
        "list.hoverForeground": "#D5D0E5",
        "list.focusForeground": "#D5D0E5",
        "quickInput.background": "#0E0D15",
        "quickInput.foreground": "#D5D0E5",
        "quickInputList.focusBackground": "#2E2841",
        "quickInputList.focusForeground": "#D5D0E5",
        "quickInputList.focusIconForeground": "#D5D0E5",
        "editorSuggestWidget.selectedBackground": "#2E2841",
        "editorSuggestWidget.foreground": "#D5D0E5",
        "editorWidget.foreground": "#D5D0E5",
        "editorHoverWidget.foreground": "#D5D0E5",
        "terminal.selectionBackground": "#2E2841",
        "terminal.inactiveSelectionBackground": "#201D2D",
        "terminalCursor.foreground": "#C48EF0",
        "terminalCursor.background": "#11101A",
        "icon.foreground": "#968BAD",
      },
      light: {
        "list.hoverBackground": "#D8CBEA",
        "list.focusBackground": "#CFBCE6",
        "list.activeSelectionBackground": "#CFBCE6",
        "list.inactiveSelectionBackground": "#DED4EC",
        "list.hoverForeground": "#4D455F",
        "list.focusForeground": "#4D455F",
        "quickInput.background": "#E9E7F1",
        "quickInput.foreground": "#4D455F",
        "quickInputList.focusBackground": "#CFBCE6",
        "quickInputList.focusForeground": "#4D455F",
        "quickInputList.focusIconForeground": "#4D455F",
        "editorSuggestWidget.selectedBackground": "#CFBCE6",
        "activityBar.inactiveForeground": "#756D86",
        "icon.foreground": "#756D86",
      },
    },
    hues: {
      string: "#7CE4D8",
      callable: "#80C0E8",
      type: "#E4C478",
      constant: "#F0A888",
      enum: "#B4D088",
    },
    variantHues: {
      light: {
        string: "#007A73",
        callable: "#286FA3",
        type: "#9A6A00",
        constant: "#B35435",
        enum: "#5F7F1B",
      },
    },
  },
  {
    fileStem: "LeoMorning",
    label: "Leo Morning",
    accent: "#88D4A0",
    text: "#DDE8E0",
    texts: {
      light: "#1F3429",
    },
    backgrounds: {
      dark: "#161C19",
      deep: "#0D100F",
      light: "#F1FAF4",
    },
    paletteOverrides: {
      dark: {
        base: "#18211D",
        mantle: "#141C18",
        crust: "#101612",
        surface0: "#253029",
        surface1: "#334139",
        surface2: "#45564B",
        overlay0: "#647267",
        overlay1: "#7C8C81",
        overlay2: "#94A499",
        subtext0: "#AAB9AF",
        subtext1: "#C0CEC4",
        text: "#D2DED5",
      },
      deep: {
        base: "#101511",
        mantle: "#0D120F",
        crust: "#090D0B",
        surface0: "#1D251F",
        surface1: "#2A352D",
        surface2: "#3B4A40",
        overlay0: "#5B675E",
        overlay1: "#748279",
        overlay2: "#8E9D92",
        subtext0: "#A2B1A6",
        subtext1: "#B9C7BD",
        text: "#CEDAD1",
      },
      light: {
        base: "#EEF6F0",
        mantle: "#E4ECE6",
        crust: "#D8E1DA",
        surface0: "#E8F0EA",
        surface1: "#DDE6E0",
        surface2: "#D1DCD5",
        overlay0: "#A8B5AC",
        overlay1: "#89988F",
        overlay2: "#6E7F75",
        subtext0: "#5F7167",
        subtext1: "#506258",
        text: "#3A4D42",
      },
    },
    accents: {
      light: "#2F8F57",
    },
    colorOverrides: {
      dark: {
        "list.hoverBackground": "#253029",
        "list.focusBackground": "#334139",
        "list.activeSelectionBackground": "#334139",
        "list.inactiveSelectionBackground": "#253029",
        "list.hoverForeground": "#D2DED5",
        "list.focusForeground": "#D2DED5",
        "quickInput.background": "#141C18",
        "quickInput.foreground": "#D2DED5",
        "quickInputList.focusBackground": "#334139",
        "quickInputList.focusForeground": "#D2DED5",
        "quickInputList.focusIconForeground": "#D2DED5",
        "editorSuggestWidget.selectedBackground": "#334139",
        "editorSuggestWidget.foreground": "#D2DED5",
        "editorWidget.foreground": "#D2DED5",
        "editorHoverWidget.foreground": "#D2DED5",
        "terminal.selectionBackground": "#334139",
        "terminal.inactiveSelectionBackground": "#253029",
        "terminalCursor.foreground": "#88D4A0",
        "terminalCursor.background": "#18211D",
        "icon.foreground": "#94A499",
      },
      deep: {
        "list.hoverBackground": "#1D251F",
        "list.focusBackground": "#2A352D",
        "list.activeSelectionBackground": "#2A352D",
        "list.inactiveSelectionBackground": "#1D251F",
        "list.hoverForeground": "#CEDAD1",
        "list.focusForeground": "#CEDAD1",
        "quickInput.background": "#0D120F",
        "quickInput.foreground": "#CEDAD1",
        "quickInputList.focusBackground": "#2A352D",
        "quickInputList.focusForeground": "#CEDAD1",
        "quickInputList.focusIconForeground": "#CEDAD1",
        "editorSuggestWidget.selectedBackground": "#2A352D",
        "editorSuggestWidget.foreground": "#CEDAD1",
        "editorWidget.foreground": "#CEDAD1",
        "editorHoverWidget.foreground": "#CEDAD1",
        "terminal.selectionBackground": "#2A352D",
        "terminal.inactiveSelectionBackground": "#1D251F",
        "terminalCursor.foreground": "#88D4A0",
        "terminalCursor.background": "#101511",
        "icon.foreground": "#8E9D92",
      },
      light: {
        "list.hoverBackground": "#C3DBCC",
        "list.focusBackground": "#B1D2BE",
        "list.activeSelectionBackground": "#B1D2BE",
        "list.inactiveSelectionBackground": "#CEE1D5",
        "list.hoverForeground": "#3A4D42",
        "list.focusForeground": "#3A4D42",
        "quickInput.background": "#E4ECE6",
        "quickInput.foreground": "#3A4D42",
        "quickInputList.focusBackground": "#B1D2BE",
        "quickInputList.focusForeground": "#3A4D42",
        "quickInputList.focusIconForeground": "#3A4D42",
        "editorSuggestWidget.selectedBackground": "#B1D2BE",
        "activityBar.inactiveForeground": "#6E7F75",
        "icon.foreground": "#6E7F75",
      },
    },
    hues: {
      string: "#72D4C4",
      callable: "#80B4DC",
      type: "#D4B462",
      constant: "#E898A8",
      enum: "#A0D892",
    },
    variantHues: {
      light: {
        string: "#007A68",
        callable: "#286D9F",
        type: "#8A6500",
        constant: "#B35672",
        enum: "#438A32",
      },
    },
  },
];

function resolveDefinition(definition, variant) {
  return {
    ...definition,
    accent: definition.accents?.[variant] ?? definition.accent,
    error: variant === "light" ? "#C93D45" : SHARED.error,
    hues: {
      ...definition.hues,
      ...(definition.variantHues?.[variant] ?? {}),
    },
    text: definition.texts?.[variant] ?? definition.text,
    paletteOverrides: definition.paletteOverrides?.[variant] ?? {},
    colorOverrides: definition.colorOverrides?.[variant] ?? {},
  };
}

function clampChannel(value) {
  return Math.max(0, Math.min(255, Math.round(value)));
}

function hexToRgb(color) {
  const hex = color.replace("#", "");
  if (hex.length !== 6) {
    throw new Error(`Expected 6-digit hex color, received ${color}`);
  }

  return {
    r: Number.parseInt(hex.slice(0, 2), 16),
    g: Number.parseInt(hex.slice(2, 4), 16),
    b: Number.parseInt(hex.slice(4, 6), 16),
  };
}

function rgbToHex({ r, g, b }) {
  return `#${[r, g, b]
    .map((channel) => clampChannel(channel).toString(16).padStart(2, "0"))
    .join("")
    .toUpperCase()}`;
}

function mix(colorA, colorB, amount) {
  const from = hexToRgb(colorA);
  const to = hexToRgb(colorB);

  return rgbToHex({
    r: from.r + (to.r - from.r) * amount,
    g: from.g + (to.g - from.g) * amount,
    b: from.b + (to.b - from.b) * amount,
  });
}

function shade(color, amount) {
  if (amount === 0) {
    return color;
  }

  return amount > 0 ? mix(color, "#FFFFFF", amount) : mix(color, "#000000", -amount);
}

function opacity(color, alpha) {
  const hex = color.replace("#", "").toUpperCase();
  const channel = clampChannel(alpha * 255)
    .toString(16)
    .padStart(2, "0")
    .toUpperCase();

  return `#${hex}${channel}`;
}

function buildPalette(definition, variant) {
  const base = definition.backgrounds[variant];
  const text = mix(base, definition.text, 0.9);
  const mantle = shade(base, -0.09);
  const crust = shade(base, -0.16);
  const surface0 = mix(base, text, 0.08);
  const surface1 = mix(base, text, 0.14);
  const surface2 = mix(base, text, 0.22);
  const overlay0 = mix(surface2, text, 0.28);
  const overlay1 = mix(surface2, text, 0.45);
  const overlay2 = mix(surface2, text, 0.62);
  const generatedPalette = {
    base,
    text,
    mantle,
    crust,
    surface0,
    surface1,
    surface2,
    overlay0,
    overlay1,
    overlay2,
  };
  const palette = {
    ...generatedPalette,
    ...definition.paletteOverrides,
  };

  return {
    ...palette,
    accentMuted: palette.accentMuted ?? mix(palette.text, definition.accent, 0.36),
    parameter: palette.parameter ?? mix(palette.text, definition.accent, 0.24),
    regex: palette.regex ?? mix(definition.hues.string, definition.accent, 0.35),
    escape: palette.escape ?? mix(definition.hues.string, definition.accent, 0.48),
  };
}

function buildColors(definition, variant) {
  const palette = buildPalette(definition, variant);
  const error = definition.error ?? SHARED.error;
  const { hues } = definition;
  const isLight = variant === "light";
  const transparent = "#00000000";
  const shadow = opacity("#000000", isLight ? 0.12 : 0.36);
  const selection = opacity(definition.accent, isLight ? 0.28 : 0.35);
  const accentSubtle = opacity(definition.accent, isLight ? 0.16 : 0.22);
  const dropBackground = opacity(definition.accent, isLight ? 0.22 : 0.28);

  return {
    foreground: palette.text,
    disabledForeground: palette.overlay0,
    descriptionForeground: palette.overlay1,
    errorForeground: error,
    "selection.background": selection,
    "widget.shadow": shadow,
    "widget.border": palette.surface2,
    "sash.hoverBorder": definition.accent,
    "icon.foreground": palette.overlay2,
    "textBlockQuote.background": palette.mantle,
    "textBlockQuote.border": palette.surface2,
    "textCodeBlock.background": palette.mantle,
    "textLink.foreground": hues.callable,
    "textLink.activeForeground": definition.accent,
    "textPreformat.foreground": palette.text,
    "textSeparator.foreground": palette.surface2,
    "editor.background": palette.base,
    "editor.foreground": palette.text,
    "editor.lineHighlightBorder": transparent,
    "editorCursor.foreground": definition.accent,
    "editorCursor.background": palette.base,
    "editor.lineHighlightBackground": opacity(palette.text, 0.06),
    "editor.selectionBackground": opacity(palette.overlay2, 0.24),
    "editor.inactiveSelectionBackground": opacity(palette.overlay1, 0.18),
    "editor.selectionHighlightBackground": opacity(palette.overlay2, 0.12),
    "editor.selectionHighlightBorder": transparent,
    "editor.wordHighlightBackground": opacity(palette.overlay2, 0.14),
    "editor.wordHighlightStrongBackground": opacity(hues.callable, 0.18),
    "editor.wordHighlightBorder": transparent,
    "editor.wordHighlightStrongBorder": transparent,
    "editor.findMatchBackground": opacity(hues.constant, 0.34),
    "editor.findMatchHighlightBackground": opacity(hues.callable, 0.24),
    "editor.findMatchBorder": hues.constant,
    "editor.findMatchHighlightBorder": transparent,
    "editor.findRangeHighlightBackground": accentSubtle,
    "editor.hoverHighlightBackground": opacity(definition.accent, isLight ? 0.12 : 0.18),
    "editor.rangeHighlightBackground": opacity(palette.overlay2, isLight ? 0.1 : 0.16),
    "editor.rangeHighlightBorder": transparent,
    "editor.foldBackground": opacity(palette.surface1, isLight ? 0.55 : 0.42),
    "editor.linkedEditingBackground": accentSubtle,
    "editor.snippetTabstopHighlightBackground": opacity(hues.callable, 0.18),
    "editor.snippetFinalTabstopHighlightBorder": hues.callable,
    "editor.inlineValuesForeground": palette.overlay2,
    "editor.inlineValuesBackground": palette.surface0,
    "editorCodeLens.foreground": palette.overlay1,
    "editorLink.activeForeground": hues.callable,
    "editorRuler.foreground": palette.surface1,
    "editorGhostText.foreground": palette.overlay0,
    "editorGhostText.background": transparent,
    "editorGhostText.border": transparent,
    "editorWatermark.foreground": opacity(palette.overlay0, 0.55),
    "editorLightBulb.foreground": hues.type,
    "editorLightBulbAutoFix.foreground": hues.enum,
    "editorLineNumber.foreground": palette.overlay0,
    "editorLineNumber.activeForeground": definition.accent,
    "editorLineNumber.dimmedForeground": opacity(palette.overlay0, 0.65),
    "editorIndentGuide.background": palette.surface1,
    "editorIndentGuide.activeBackground": palette.surface2,
    "editorWhitespace.foreground": opacity(palette.overlay2, 0.35),
    "editorBracketMatch.background": opacity(palette.overlay2, 0.1),
    "editorBracketMatch.border": palette.overlay2,
    "editorBracketHighlight.foreground1": definition.accent,
    "editorBracketHighlight.foreground2": hues.string,
    "editorBracketHighlight.foreground3": hues.type,
    "editorBracketHighlight.foreground4": hues.constant,
    "editorBracketHighlight.foreground5": hues.callable,
    "editorBracketHighlight.foreground6": hues.enum,
    "editorError.foreground": error,
    "editorWarning.foreground": hues.constant,
    "editorInfo.foreground": hues.callable,
    "editorGutter.modifiedBackground": hues.callable,
    "editorGutter.addedBackground": hues.enum,
    "editorGutter.deletedBackground": error,
    "editorGutter.background": palette.base,
    "editorGutter.commentRangeForeground": palette.overlay1,
    "editorGutter.foldingControlForeground": palette.overlay2,
    "editorOverviewRuler.border": palette.surface1,
    "editorOverviewRuler.errorForeground": error,
    "editorOverviewRuler.warningForeground": hues.constant,
    "editorOverviewRuler.infoForeground": hues.callable,
    "editorOverviewRuler.findMatchForeground": hues.constant,
    "editorOverviewRuler.modifiedForeground": hues.callable,
    "editorOverviewRuler.addedForeground": hues.enum,
    "editorOverviewRuler.deletedForeground": error,
    "editorOverviewRuler.selectionHighlightForeground": palette.overlay2,
    "editorOverviewRuler.wordHighlightForeground": palette.overlay2,
    "editorOverviewRuler.wordHighlightStrongForeground": hues.callable,
    "editorStickyScroll.background": palette.base,
    "editorStickyScrollHover.background": palette.surface0,
    "editorStickyScroll.border": palette.surface1,
    "editorInlayHint.background": palette.surface0,
    "editorInlayHint.foreground": palette.overlay1,
    "editorInlayHint.typeBackground": palette.surface0,
    "editorInlayHint.typeForeground": palette.overlay2,
    "editorInlayHint.parameterBackground": palette.surface0,
    "editorInlayHint.parameterForeground": palette.overlay1,
    "sideBar.background": palette.mantle,
    "sideBar.foreground": palette.text,
    "sideBar.border": transparent,
    "sideBar.dropBackground": dropBackground,
    "sideBarTitle.foreground": definition.accent,
    "sideBarSectionHeader.background": palette.mantle,
    "sideBarSectionHeader.foreground": palette.text,
    "sideBarSectionHeader.border": palette.surface1,
    "list.activeSelectionBackground": palette.surface0,
    "list.activeSelectionForeground": palette.text,
    "list.hoverBackground": opacity(palette.surface0, 0.55),
    "list.hoverForeground": palette.text,
    "list.focusBackground": palette.surface0,
    "list.focusForeground": palette.text,
    "list.focusOutline": transparent,
    "list.activeSelectionIconForeground": definition.accent,
    "list.highlightForeground": definition.accent,
    "list.inactiveSelectionBackground": palette.surface0,
    "list.inactiveSelectionForeground": palette.text,
    "list.inactiveSelectionIconForeground": palette.overlay2,
    "list.dropBackground": dropBackground,
    "list.errorForeground": error,
    "list.warningForeground": hues.constant,
    "list.invalidItemForeground": error,
    "list.deemphasizedForeground": palette.overlay0,
    "list.filterMatchBackground": accentSubtle,
    "list.filterMatchBorder": definition.accent,
    "tree.indentGuidesStroke": palette.surface2,
    "tree.inactiveIndentGuidesStroke": palette.surface1,
    "tree.tableColumnsBorder": palette.surface1,
    "tree.tableOddRowsBackground": opacity(palette.surface0, isLight ? 0.38 : 0.28),
    "activityBar.background": palette.crust,
    "activityBar.foreground": definition.accent,
    "activityBar.inactiveForeground": palette.overlay0,
    "activityBar.border": transparent,
    "activityBar.activeBorder": transparent,
    "activityBar.activeBackground": transparent,
    "activityBar.activeFocusBorder": transparent,
    "activityBar.dropBorder": definition.accent,
    "activityBarBadge.background": definition.accent,
    "activityBarBadge.foreground": palette.crust,
    "statusBar.background": palette.crust,
    "statusBar.foreground": palette.text,
    "statusBar.border": transparent,
    "statusBar.focusBorder": definition.accent,
    "statusBarItem.activeBackground": palette.surface1,
    "statusBarItem.hoverBackground": palette.surface0,
    "statusBarItem.focusBorder": definition.accent,
    "statusBarItem.prominentBackground": palette.surface1,
    "statusBarItem.prominentHoverBackground": palette.surface2,
    "statusBarItem.remoteBackground": definition.accent,
    "statusBarItem.remoteForeground": palette.crust,
    "statusBarItem.errorBackground": error,
    "statusBarItem.errorForeground": palette.crust,
    "statusBarItem.warningBackground": hues.constant,
    "statusBarItem.warningForeground": palette.crust,
    "statusBar.debuggingBackground": hues.constant,
    "statusBar.debuggingForeground": palette.crust,
    "statusBar.noFolderBackground": palette.crust,
    "titleBar.activeBackground": palette.crust,
    "titleBar.activeForeground": palette.text,
    "titleBar.inactiveBackground": palette.crust,
    "titleBar.inactiveForeground": palette.overlay0,
    "titleBar.border": transparent,
    "editorGroupHeader.tabsBackground": palette.crust,
    "editorGroupHeader.noTabsBackground": palette.crust,
    "editorGroupHeader.border": transparent,
    "editorGroup.border": palette.surface1,
    "editorGroup.dropBackground": dropBackground,
    "editorGroup.emptyBackground": palette.base,
    "editorGroup.focusedEmptyBorder": definition.accent,
    "editorPane.background": palette.base,
    "sideBySideEditor.horizontalBorder": palette.surface1,
    "sideBySideEditor.verticalBorder": palette.surface1,
    "tab.activeBackground": palette.base,
    "tab.inactiveBackground": palette.mantle,
    "tab.activeForeground": definition.accent,
    "tab.inactiveForeground": palette.overlay0,
    "tab.activeBorder": transparent,
    "tab.activeBorderTop": definition.accent,
    "tab.activeModifiedBorder": hues.callable,
    "tab.inactiveModifiedBorder": opacity(hues.callable, 0.65),
    "tab.unfocusedActiveModifiedBorder": opacity(hues.callable, 0.5),
    "tab.unfocusedInactiveModifiedBorder": opacity(hues.callable, 0.35),
    "tab.hoverForeground": palette.text,
    "tab.hoverBackground": shade(palette.base, 0.04),
    "tab.hoverBorder": transparent,
    "tab.unfocusedActiveBackground": palette.base,
    "tab.unfocusedActiveForeground": palette.overlay2,
    "tab.unfocusedActiveBorder": transparent,
    "tab.unfocusedActiveBorderTop": opacity(definition.accent, 0.65),
    "tab.unfocusedInactiveBackground": palette.mantle,
    "tab.unfocusedInactiveForeground": palette.overlay0,
    "tab.unfocusedHoverBackground": palette.surface0,
    "tab.unfocusedHoverForeground": palette.overlay2,
    "tab.lastPinnedBorder": palette.surface2,
    "tab.border": palette.mantle,
    "panel.background": palette.base,
    "panel.border": palette.surface2,
    "panel.dropBorder": definition.accent,
    "panelInput.border": palette.surface2,
    "panelTitle.activeForeground": palette.text,
    "panelTitle.activeBorder": definition.accent,
    "panelTitle.inactiveForeground": palette.overlay0,
    "panelSection.border": palette.surface1,
    "panelSection.dropBackground": dropBackground,
    "panelSectionHeader.background": palette.mantle,
    "panelSectionHeader.foreground": palette.text,
    "panelSectionHeader.border": palette.surface1,
    "terminal.background": palette.base,
    "terminal.foreground": palette.text,
    "terminal.border": palette.surface1,
    "terminal.selectionBackground": palette.surface1,
    "terminal.inactiveSelectionBackground": palette.surface0,
    "terminalCursor.foreground": definition.accent,
    "terminalCursor.background": palette.base,
    "terminal.dropBackground": dropBackground,
    "terminal.findMatchBackground": opacity(hues.constant, 0.34),
    "terminal.findMatchBorder": hues.constant,
    "terminal.findMatchHighlightBackground": opacity(hues.callable, 0.22),
    "terminal.findMatchHighlightBorder": transparent,
    "terminal.tab.activeBorder": definition.accent,
    "terminalOverviewRuler.cursorForeground": definition.accent,
    "terminalOverviewRuler.findMatchForeground": hues.constant,
    "terminalCommandDecoration.defaultBackground": palette.overlay1,
    "terminalCommandDecoration.successBackground": hues.enum,
    "terminalCommandDecoration.errorBackground": error,
    "terminal.ansiBlack": palette.surface0,
    "terminal.ansiRed": error,
    "terminal.ansiGreen": hues.enum,
    "terminal.ansiYellow": hues.type,
    "terminal.ansiBlue": hues.callable,
    "terminal.ansiMagenta": definition.accent,
    "terminal.ansiCyan": hues.string,
    "terminal.ansiWhite": palette.overlay2,
    "terminal.ansiBrightBlack": palette.overlay0,
    "terminal.ansiBrightRed": shade(error, 0.08),
    "terminal.ansiBrightGreen": shade(hues.enum, 0.08),
    "terminal.ansiBrightYellow": shade(hues.type, 0.08),
    "terminal.ansiBrightBlue": shade(hues.callable, 0.08),
    "terminal.ansiBrightMagenta": shade(definition.accent, 0.08),
    "terminal.ansiBrightCyan": shade(hues.string, 0.08),
    "terminal.ansiBrightWhite": palette.text,
    "focusBorder": definition.accent,
    "input.background": palette.surface0,
    "input.foreground": palette.text,
    "input.border": palette.surface2,
    "input.placeholderForeground": palette.overlay0,
    "inputValidation.errorBackground": opacity(error, isLight ? 0.12 : 0.18),
    "inputValidation.errorForeground": palette.text,
    "inputValidation.errorBorder": error,
    "inputValidation.warningBackground": opacity(hues.constant, isLight ? 0.14 : 0.18),
    "inputValidation.warningForeground": palette.text,
    "inputValidation.warningBorder": hues.constant,
    "inputValidation.infoBackground": opacity(hues.callable, isLight ? 0.14 : 0.18),
    "inputValidation.infoForeground": palette.text,
    "inputValidation.infoBorder": hues.callable,
    "inputOption.activeBorder": definition.accent,
    "inputOption.activeBackground": accentSubtle,
    "inputOption.activeForeground": palette.text,
    "button.background": definition.accent,
    "button.foreground": palette.crust,
    "button.border": transparent,
    "button.separator": transparent,
    "button.hoverBackground": shade(definition.accent, 0.06),
    "button.secondaryBackground": palette.surface1,
    "button.secondaryForeground": palette.text,
    "button.secondaryHoverBackground": shade(palette.surface1, 0.08),
    "checkbox.background": palette.surface1,
    "checkbox.foreground": definition.accent,
    "checkbox.border": transparent,
    "dropdown.background": palette.mantle,
    "dropdown.foreground": palette.text,
    "dropdown.border": palette.surface2,
    "dropdown.listBackground": palette.surface0,
    "badge.background": palette.surface1,
    "badge.foreground": palette.text,
    "progressBar.background": definition.accent,
    "scrollbarSlider.background": opacity(palette.surface2, 0.5),
    "scrollbarSlider.hoverBackground": palette.overlay0,
    "scrollbarSlider.activeBackground": opacity(palette.surface0, 0.45),
    "minimap.selectionHighlight": opacity(palette.surface2, 0.75),
    "minimap.background": palette.base,
    "minimap.findMatchHighlight": hues.constant,
    "minimap.selectionOccurrenceHighlight": palette.overlay2,
    "minimap.warningHighlight": hues.constant,
    "minimap.errorHighlight": error,
    "minimapGutter.addedBackground": hues.enum,
    "minimapGutter.modifiedBackground": hues.callable,
    "minimapGutter.deletedBackground": error,
    "minimapSlider.background": opacity(definition.accent, 0.2),
    "minimapSlider.hoverBackground": opacity(definition.accent, 0.4),
    "minimapSlider.activeBackground": opacity(definition.accent, 0.6),
    "menu.background": palette.mantle,
    "menu.foreground": palette.text,
    "menu.selectionBackground": palette.surface0,
    "menu.selectionForeground": palette.text,
    "menu.selectionBorder": transparent,
    "menu.separatorBackground": palette.surface2,
    "menu.border": palette.surface2,
    "menubar.selectionBackground": palette.surface0,
    "menubar.selectionForeground": palette.text,
    "menubar.selectionBorder": transparent,
    "commandCenter.background": palette.crust,
    "commandCenter.foreground": palette.text,
    "commandCenter.activeBackground": palette.surface0,
    "commandCenter.activeForeground": palette.text,
    "commandCenter.border": palette.surface2,
    "commandCenter.activeBorder": definition.accent,
    "commandCenter.inactiveForeground": palette.overlay0,
    "commandCenter.inactiveBorder": palette.surface1,
    "commandCenter.debuggingBackground": hues.constant,
    "commandCenter.debuggingForeground": palette.crust,
    "breadcrumb.foreground": palette.overlay1,
    "breadcrumb.background": palette.base,
    "breadcrumb.focusForeground": definition.accent,
    "breadcrumb.activeSelectionForeground": definition.accent,
    "breadcrumbPicker.background": palette.mantle,
    "quickInput.background": palette.mantle,
    "quickInput.foreground": palette.text,
    "quickInputList.focusBackground": palette.surface0,
    "quickInputList.focusForeground": palette.text,
    "quickInputList.focusIconForeground": definition.accent,
    "notificationCenter.border": definition.accent,
    "notificationToast.border": palette.surface2,
    "notifications.border": palette.surface2,
    "notifications.background": palette.mantle,
    "notifications.foreground": palette.text,
    "notificationCenterHeader.background": palette.crust,
    "notificationCenterHeader.foreground": palette.text,
    "notificationLink.foreground": hues.callable,
    "notificationsErrorIcon.foreground": error,
    "notificationsWarningIcon.foreground": hues.constant,
    "notificationsInfoIcon.foreground": hues.callable,
    "banner.background": palette.surface0,
    "banner.foreground": palette.text,
    "banner.iconForeground": definition.accent,
    "peekView.border": definition.accent,
    "peekViewEditor.background": palette.mantle,
    "peekViewResult.background": palette.mantle,
    "peekViewTitle.background": palette.base,
    "peekViewTitleLabel.foreground": palette.text,
    "peekViewTitleDescription.foreground": palette.overlay1,
    "peekViewResult.fileForeground": palette.text,
    "peekViewResult.lineForeground": palette.overlay1,
    "peekViewResult.selectionBackground": palette.surface0,
    "peekViewResult.selectionForeground": palette.text,
    "peekViewResult.matchHighlightBackground": opacity(hues.callable, 0.3),
    "peekViewEditorGutter.background": palette.mantle,
    "peekViewEditor.matchHighlightBackground": opacity(hues.callable, 0.3),
    "gitDecoration.modifiedResourceForeground": hues.callable,
    "gitDecoration.stageModifiedResourceForeground": hues.callable,
    "gitDecoration.renamedResourceForeground": hues.callable,
    "gitDecoration.deletedResourceForeground": error,
    "gitDecoration.stageDeletedResourceForeground": error,
    "gitDecoration.untrackedResourceForeground": hues.enum,
    "gitDecoration.ignoredResourceForeground": palette.overlay0,
    "gitDecoration.conflictingResourceForeground": definition.accent,
    "gitDecoration.submoduleResourceForeground": hues.string,
    "diffEditor.insertedTextBackground": opacity(hues.enum, 0.18),
    "diffEditor.insertedTextBorder": transparent,
    "diffEditor.insertedLineBackground": opacity(hues.enum, 0.1),
    "diffEditor.insertedLineGutterBackground": opacity(hues.enum, 0.18),
    "diffEditor.removedTextBackground": opacity(error, 0.18),
    "diffEditor.removedTextBorder": transparent,
    "diffEditor.removedLineBackground": opacity(error, 0.1),
    "diffEditor.removedLineGutterBackground": opacity(error, 0.18),
    "diffEditor.border": palette.surface1,
    "diffEditor.diagonalFill": opacity(palette.overlay0, 0.28),
    "editorWidget.background": palette.mantle,
    "editorWidget.foreground": palette.text,
    "editorWidget.border": palette.surface2,
    "editorWidget.resizeBorder": definition.accent,
    "editorSuggestWidget.background": palette.mantle,
    "editorSuggestWidget.border": palette.surface2,
    "editorSuggestWidget.foreground": palette.text,
    "editorSuggestWidget.selectedForeground": palette.text,
    "editorSuggestWidget.selectedBackground": palette.surface0,
    "editorSuggestWidget.selectedIconForeground": definition.accent,
    "editorSuggestWidget.highlightForeground": definition.accent,
    "editorSuggestWidget.focusHighlightForeground": definition.accent,
    "editorSuggestWidget.statusForeground": palette.overlay1,
    "editorHoverWidget.background": palette.mantle,
    "editorHoverWidget.foreground": palette.text,
    "editorHoverWidget.border": palette.surface2,
    "editorHoverWidget.statusBarBackground": palette.crust,
    "debugToolBar.background": palette.crust,
    "debugToolBar.border": transparent,
    "debugExceptionWidget.background": palette.crust,
    "debugExceptionWidget.border": error,
    "debugIcon.breakpointForeground": error,
    "debugIcon.breakpointDisabledForeground": palette.overlay0,
    "debugIcon.breakpointUnverifiedForeground": hues.constant,
    "debugIcon.breakpointCurrentStackframeForeground": hues.type,
    "debugIcon.breakpointStackframeForeground": hues.callable,
    "debugIcon.startForeground": hues.enum,
    "debugIcon.pauseForeground": hues.callable,
    "debugIcon.stopForeground": error,
    "debugIcon.disconnectForeground": error,
    "debugIcon.restartForeground": hues.enum,
    "debugIcon.stepOverForeground": hues.callable,
    "debugIcon.stepIntoForeground": hues.callable,
    "debugIcon.stepOutForeground": hues.callable,
    "debugIcon.continueForeground": hues.enum,
    "debugConsole.infoForeground": hues.callable,
    "debugConsole.warningForeground": hues.constant,
    "debugConsole.errorForeground": error,
    "debugConsole.sourceForeground": palette.overlay2,
    "debugConsoleInputIcon.foreground": definition.accent,
    "debugView.exceptionLabelBackground": error,
    "debugView.exceptionLabelForeground": palette.crust,
    "debugView.stateLabelBackground": palette.surface1,
    "debugView.stateLabelForeground": palette.text,
    "debugView.valueChangedHighlight": hues.constant,
    "problemsErrorIcon.foreground": error,
    "problemsWarningIcon.foreground": hues.constant,
    "problemsInfoIcon.foreground": hues.callable,
    "testing.iconFailed": error,
    "testing.iconErrored": error,
    "testing.iconPassed": hues.enum,
    "testing.iconQueued": hues.type,
    "testing.iconUnset": palette.overlay1,
    "testing.iconSkipped": palette.overlay0,
    "testing.runAction": hues.enum,
    "testing.peekBorder": definition.accent,
    "testing.peekHeaderBackground": palette.crust,
    "testing.message.error.decorationForeground": error,
    "testing.message.error.lineBackground": opacity(error, 0.12),
    "testing.message.info.decorationForeground": hues.callable,
    "testing.message.info.lineBackground": opacity(hues.callable, 0.12),
    "symbolIcon.arrayForeground": hues.constant,
    "symbolIcon.booleanForeground": hues.constant,
    "symbolIcon.classForeground": hues.type,
    "symbolIcon.colorForeground": hues.constant,
    "symbolIcon.constantForeground": hues.constant,
    "symbolIcon.constructorForeground": hues.type,
    "symbolIcon.enumeratorForeground": hues.type,
    "symbolIcon.enumeratorMemberForeground": hues.enum,
    "symbolIcon.eventForeground": hues.constant,
    "symbolIcon.fieldForeground": palette.parameter,
    "symbolIcon.fileForeground": palette.text,
    "symbolIcon.folderForeground": definition.accent,
    "symbolIcon.functionForeground": hues.callable,
    "symbolIcon.interfaceForeground": hues.type,
    "symbolIcon.keyForeground": definition.accent,
    "symbolIcon.keywordForeground": definition.accent,
    "symbolIcon.methodForeground": hues.callable,
    "symbolIcon.moduleForeground": palette.parameter,
    "symbolIcon.namespaceForeground": hues.type,
    "symbolIcon.nullForeground": error,
    "symbolIcon.numberForeground": hues.constant,
    "symbolIcon.objectForeground": palette.text,
    "symbolIcon.operatorForeground": hues.string,
    "symbolIcon.packageForeground": palette.parameter,
    "symbolIcon.propertyForeground": palette.parameter,
    "symbolIcon.referenceForeground": hues.string,
    "symbolIcon.snippetForeground": definition.accent,
    "symbolIcon.stringForeground": hues.string,
    "symbolIcon.structForeground": hues.type,
    "symbolIcon.textForeground": palette.text,
    "symbolIcon.typeParameterForeground": palette.parameter,
    "symbolIcon.unitForeground": hues.constant,
    "symbolIcon.variableForeground": palette.text,
    "settings.headerForeground": definition.accent,
    "settings.modifiedItemIndicator": hues.callable,
    "settings.dropdownBackground": palette.mantle,
    "settings.dropdownForeground": palette.text,
    "settings.dropdownBorder": palette.surface2,
    "settings.checkboxBackground": palette.surface1,
    "settings.checkboxForeground": definition.accent,
    "settings.checkboxBorder": transparent,
    "settings.textInputBackground": palette.surface0,
    "settings.textInputForeground": palette.text,
    "settings.textInputBorder": palette.surface2,
    "settings.numberInputBackground": palette.surface0,
    "settings.numberInputForeground": palette.text,
    "settings.numberInputBorder": palette.surface2,
    "settings.rowHoverBackground": opacity(palette.surface0, isLight ? 0.55 : 0.45),
    "settings.focusedRowBackground": palette.surface0,
    "settings.focusedRowBorder": definition.accent,
    "welcomePage.background": palette.base,
    "welcomePage.buttonBackground": palette.surface1,
    "welcomePage.buttonHoverBackground": palette.surface2,
    "welcomePage.tileBackground": palette.mantle,
    "welcomePage.tileHoverBackground": palette.surface0,
    "welcomePage.tileBorder": palette.surface1,
    "walkThrough.embeddedEditorBackground": palette.mantle,
    "notebook.editorBackground": palette.base,
    "notebook.cellBorderColor": palette.surface1,
    "notebook.cellHoverBackground": palette.surface0,
    "notebook.cellInsertionIndicator": definition.accent,
    "notebook.cellStatusBarItemHoverBackground": palette.surface1,
    "notebook.cellToolbarSeparator": palette.surface2,
    "notebook.focusedCellBackground": palette.surface0,
    "notebook.focusedCellBorder": definition.accent,
    "notebook.focusedEditorBorder": definition.accent,
    "notebook.inactiveFocusedCellBorder": palette.surface2,
    "notebook.selectedCellBackground": palette.surface0,
    "notebook.selectedCellBorder": definition.accent,
    "notebook.symbolHighlightBackground": accentSubtle,
    "extensionButton.prominentBackground": definition.accent,
    "extensionButton.prominentForeground": palette.crust,
    "extensionButton.prominentHoverBackground": shade(definition.accent, 0.06),
    "extensionIcon.starForeground": hues.type,
    "extensionIcon.verifiedForeground": hues.callable,
    "extensionIcon.preReleaseForeground": definition.accent,
    "extensionIcon.sponsorForeground": hues.constant,
    "charts.foreground": palette.text,
    "charts.lines": palette.overlay0,
    "charts.red": error,
    "charts.blue": hues.callable,
    "charts.yellow": hues.type,
    "charts.orange": hues.constant,
    "charts.green": hues.enum,
    "charts.purple": definition.accent,
    ...definition.colorOverrides,
  };
}

function buildSemanticTokens(definition, variant) {
  const palette = buildPalette(definition, variant);
  const error = definition.error ?? SHARED.error;
  const { hues } = definition;

  return {
    enumMember: { foreground: hues.enum },
    function: { foreground: hues.callable, fontStyle: "italic" },
    method: { foreground: hues.callable, fontStyle: "italic" },
    keyword: { foreground: definition.accent },
    number: { foreground: hues.constant },
    boolean: { foreground: hues.constant },
    parameter: { foreground: palette.parameter, fontStyle: "italic" },
    property: { foreground: palette.text },
    "variable.defaultLibrary": { foreground: palette.parameter },
    "variable.readonly": { foreground: palette.text },
    "property.readonly": { foreground: palette.text },
    class: { foreground: hues.type, fontStyle: "italic" },
    type: { foreground: hues.type, fontStyle: "italic" },
    interface: { foreground: hues.type, fontStyle: "italic" },
    enum: { foreground: hues.type, fontStyle: "italic" },
    namespace: { foreground: hues.type },
    typeParameter: { foreground: palette.parameter },
    decorator: { foreground: hues.constant, fontStyle: "italic" },
    macro: { foreground: hues.callable },
    selfKeyword: { foreground: error },
  };
}

function buildTokenColors(definition, variant) {
  const palette = buildPalette(definition, variant);
  const error = definition.error ?? SHARED.error;
  const { hues } = definition;

  return [
    {
      scope: ["comment", "punctuation.definition.comment"],
      settings: {
        foreground: palette.overlay0,
        fontStyle: "italic",
      },
    },
    {
      scope: ["text", "source", "variable", "variable.other.readwrite"],
      settings: {
        foreground: palette.text,
      },
    },
    {
      scope: ["keyword", "keyword.control", "keyword.other"],
      settings: {
        foreground: definition.accent,
        fontStyle: "",
      },
    },
    {
      scope: ["storage.type", "storage.modifier", "storage"],
      settings: {
        foreground: definition.accent,
        fontStyle: "",
      },
    },
    {
      scope: ["keyword.control.import", "keyword.control.export", "keyword.control.from"],
      settings: {
        foreground: palette.accentMuted,
        fontStyle: "",
      },
    },
    {
      scope: "string",
      settings: {
        foreground: hues.string,
      },
    },
    {
      scope: "string.regexp",
      settings: {
        foreground: palette.regex,
      },
    },
    {
      scope: "constant.character.escape",
      settings: {
        foreground: palette.escape,
      },
    },
    {
      scope: "variable.parameter",
      settings: {
        foreground: palette.parameter,
        fontStyle: "italic",
      },
    },
    {
      scope: ["variable.other.property", "support.variable.property", "variable.object.property"],
      settings: {
        foreground: palette.text,
      },
    },
    {
      scope: ["entity.name.function", "support.function", "meta.function-call", "meta.function-call.method"],
      settings: {
        foreground: hues.callable,
        fontStyle: "italic",
      },
    },
    {
      scope: ["entity.name.type", "support.class", "entity.name.class", "entity.name.namespace"],
      settings: {
        foreground: hues.type,
        fontStyle: "italic",
      },
    },
    {
      scope: ["entity.name.enum", "entity.name.type.enum"],
      settings: {
        foreground: hues.type,
        fontStyle: "italic",
      },
    },
    {
      scope: ["constant", "constant.language", "support.constant", "variable.other.constant"],
      settings: {
        foreground: hues.constant,
      },
    },
    {
      scope: ["constant.numeric", "number"],
      settings: {
        foreground: hues.constant,
      },
    },
    {
      scope: ["keyword.operator", "operator", "punctuation.accessor"],
      settings: {
        foreground: hues.string,
      },
    },
    {
      scope: "punctuation",
      settings: {
        foreground: palette.overlay1,
      },
    },
    {
      scope: [
        "punctuation.definition.block",
        "punctuation.definition.parameters",
        "punctuation.section",
        "punctuation.definition.arguments",
      ],
      settings: {
        foreground: palette.overlay2,
      },
    },
    {
      scope: "entity.name.tag",
      settings: {
        foreground: definition.accent,
      },
    },
    {
      scope: "entity.other.attribute-name",
      settings: {
        foreground: hues.callable,
        fontStyle: "italic",
      },
    },
    {
      scope: ["meta.decorator", "punctuation.decorator"],
      settings: {
        foreground: hues.constant,
        fontStyle: "italic",
      },
    },
    {
      scope: ["support.type", "meta.type", "meta.type-alias"],
      settings: {
        foreground: hues.type,
      },
    },
    {
      scope: ["support.function.builtin", "variable.language.this"],
      settings: {
        foreground: error,
      },
    },
    {
      scope: "markup.heading",
      settings: {
        foreground: definition.accent,
        fontStyle: "bold",
      },
    },
    {
      scope: "markup.bold",
      settings: {
        fontStyle: "bold",
      },
    },
    {
      scope: "markup.italic",
      settings: {
        fontStyle: "italic",
      },
    },
    {
      scope: "markup.underline",
      settings: {
        fontStyle: "underline",
      },
    },
    {
      scope: "markup.inserted",
      settings: {
        foreground: hues.enum,
      },
    },
    {
      scope: "markup.deleted",
      settings: {
        foreground: error,
      },
    },
    {
      scope: "markup.changed",
      settings: {
        foreground: hues.callable,
      },
    },
    {
      scope: ["markup.inline.raw", "markup.fenced_code"],
      settings: {
        foreground: hues.string,
      },
    },
    {
      scope: "meta.embedded",
      settings: {
        foreground: palette.text,
      },
    },
    {
      scope: "invalid",
      settings: {
        foreground: error,
        fontStyle: "underline",
      },
    },
  ];
}

function buildTheme(definition, variant) {
  const themeDefinition = resolveDefinition(definition, variant);
  const variantLabel = variant === "dark" ? "Dark" : variant === "deep" ? "Dark Deep" : "Light";

  return {
    $schema: "vscode://schemas/color-theme",
    name: `${themeDefinition.label} ${variantLabel}`,
    type: variant === "light" ? "light" : "vs-dark",
    colors: buildColors(themeDefinition, variant),
    semanticHighlighting: true,
    semanticTokenColors: buildSemanticTokens(themeDefinition, variant),
    tokenColors: buildTokenColors(themeDefinition, variant),
  };
}

async function writeTheme(definition, variant) {
  const theme = buildTheme(definition, variant);
  const fileName =
    variant === "dark"
      ? `${definition.fileStem}-dark-color-theme.json`
      : variant === "deep"
        ? `${definition.fileStem}-dark-deep-color-theme.json`
        : `${definition.fileStem}-light-color-theme.json`;

  await fs.writeFile(
    path.join(themesDir, fileName),
    `${JSON.stringify(theme, null, "\t")}\n`,
    "utf8",
  );
}

async function main() {
  await Promise.all(
    THEME_DEFINITIONS.flatMap((definition) => [
      writeTheme(definition, "dark"),
      writeTheme(definition, "deep"),
      writeTheme(definition, "light"),
    ]),
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
